# Generated by Django 4.0.1 on 2022-01-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='user-images')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('conversations', models.CharField(max_length=1000, null=True)),
                ('contacts', models.CharField(max_length=1000, null=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='message-images')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='apis.person')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='apis.person')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('messages', models.ManyToManyField(blank=True, to='apis.Message')),
                ('person_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_1', to='apis.person')),
                ('person_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_2', to='apis.person')),
            ],
        ),
    ]
