# Generated by Django 4.0.1 on 2022-01-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_conversation_person_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='c_id',
            new_name='conversation_id',
        ),
    ]
